/* This file is auto-generated by terra-dev-site's generate-component-config config. */

// Component Examples
import TerraClinicalApplicationIndex from './packages/terra-clinical-application/examples/Index.site-page';
import TerraClinicalSiteIndex from './packages/terra-clinical-site/src/examples/action-header/Index';
import TerraClinicalSiteIndex1 from './packages/terra-clinical-site/src/examples/detail-view/Index';
import TerraClinicalSiteIndex2 from './packages/terra-clinical-site/src/examples/error-view/Index';
import TerraClinicalSiteIndex3 from './packages/terra-clinical-site/src/examples/header/Index';
import TerraClinicalSiteIndex4 from './packages/terra-clinical-site/src/examples/item-collection/Index';
import TerraClinicalSiteIndex5 from './packages/terra-clinical-site/src/examples/item-display/Index';
import TerraClinicalSiteIndex6 from './packages/terra-clinical-site/src/examples/item-view/Index';
import TerraClinicalSiteIndex7 from './packages/terra-clinical-site/src/examples/label-value-view/Index';
import TerraClinicalSiteIndex8 from './packages/terra-clinical-site/src/examples/no-data-view/Index';
import TerraClinicalSiteIndex9 from './packages/terra-clinical-site/src/examples/onset-picker/Index';

// Component Test Examples
import BackActionHeader from './packages/terra-clinical-action-header/examples/test-examples/BackActionHeader.example';
import BackCloseActionHeader from './packages/terra-clinical-action-header/examples/test-examples/BackCloseActionHeader.example';
import ChildrenActionHeader from './packages/terra-clinical-action-header/examples/test-examples/ChildrenActionHeader.example';
import CloseActionHeader from './packages/terra-clinical-action-header/examples/test-examples/CloseActionHeader.example';
import DefaultActionHeader from './packages/terra-clinical-action-header/examples/test-examples/DefaultActionHeader.example';
import KeepCloseButtonActionHeader from './packages/terra-clinical-action-header/examples/test-examples/KeepCloseButtonActionHeader.example';
import MaximizeActionHeader from './packages/terra-clinical-action-header/examples/test-examples/MaximizeActionHeader.example';
import MinimizeActionHeader from './packages/terra-clinical-action-header/examples/test-examples/MinimizeActionHeader.example';
import PreviousNextActionHeader from './packages/terra-clinical-action-header/examples/test-examples/PreviousNextActionHeader.example';
import TitleActionHeader from './packages/terra-clinical-action-header/examples/test-examples/TitleActionHeader.example';
import DefaultApplication from './packages/terra-clinical-application/examples/test-examples/DefaultApplication.example';
import NoAppDelegateApplication from './packages/terra-clinical-application/examples/test-examples/NoAppDelegateApplication.example';
import LargeItemList from './packages/terra-clinical-detail-view/tests/nightwatch/DetailList/LargeItemList';
import NormalItemList from './packages/terra-clinical-detail-view/tests/nightwatch/DetailList/NormalItemList';
import DefaultListItem from './packages/terra-clinical-detail-view/tests/nightwatch/DetailListItem/DefaultListItem';
import DetailViewDivided from './packages/terra-clinical-detail-view/tests/nightwatch/DetailView/DetailViewDivided';
import DetailViewNoDivider from './packages/terra-clinical-detail-view/tests/nightwatch/DetailView/DetailViewNoDivider';
import ButtonErrorView from './packages/terra-clinical-error-view/tests/nightwatch/ButtonErrorView';
import DefaultErrorView from './packages/terra-clinical-error-view/tests/nightwatch/DefaultErrorView';
import HiddenErrorView from './packages/terra-clinical-error-view/tests/nightwatch/HiddenErrorView';
import TextErrorView from './packages/terra-clinical-error-view/tests/nightwatch/TextErrorView';
import DefaultHeader from './packages/terra-clinical-header/examples/test-examples/DefaultHeader.example';
import LeftAndRightContentHeader from './packages/terra-clinical-header/examples/test-examples/LeftAndRightContentHeader.example';
import LeftAndRightContentSubheader from './packages/terra-clinical-header/examples/test-examples/LeftAndRightContentSubheader.example';
import LeftContentHeader from './packages/terra-clinical-header/examples/test-examples/LeftContentHeader.example';
import LongTitleAndContentHeader from './packages/terra-clinical-header/examples/test-examples/LongTitleAndContentHeader.example';
import LongTitleHeader from './packages/terra-clinical-header/examples/test-examples/LongTitleHeader.example';
import NoTitleRightContentHeader from './packages/terra-clinical-header/examples/test-examples/NoTitleRightContentHeader.example';
import RightContentHeader from './packages/terra-clinical-header/examples/test-examples/RightContentHeader.example';
import TitleHeader from './packages/terra-clinical-header/examples/test-examples/TitleHeader.example';
import ItemCollectionAllElements from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionAllElements.example';
import ItemCollectionItemStyles from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionItemStyles.example';
import ItemCollectionListStyles from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionListStyles.example';
import ItemCollectionSelectable from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionSelectable.example';
import ItemCollectionTableStyles from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionTableStyles.example';
import ItemCollectionVaryingItems from './packages/terra-clinical-item-collection/examples/test-examples/ItemCollectionVaryingItems.example';
import DefaultItemComment from './packages/terra-clinical-item-display/tests/nightwatch/comment/DefaultItemComment';
import TextItemComment from './packages/terra-clinical-item-display/tests/nightwatch/comment/TextItemComment';
import DefaultItemDisplay from './packages/terra-clinical-item-display/tests/nightwatch/display/DefaultItemDisplay';
import DisabledItemDisplay from './packages/terra-clinical-item-display/tests/nightwatch/display/DisabledItemDisplay';
import IconItemDisplay from './packages/terra-clinical-item-display/tests/nightwatch/display/IconItemDisplay';
import ScalingIconItemDisplay from './packages/terra-clinical-item-display/tests/nightwatch/display/ScalingIconItemDisplay';
import TextStyleItemDisplay from './packages/terra-clinical-item-display/tests/nightwatch/display/TextStyleItemDisplay';
import AccessoryItemView from './packages/terra-clinical-item-view/examples/test-examples/AccessoryItemView.example';
import CommentItemView from './packages/terra-clinical-item-view/examples/test-examples/CommentItemView.example';
import DefaultItemView from './packages/terra-clinical-item-view/examples/test-examples/DefaultItemView.example';
import DisplaysItemView from './packages/terra-clinical-item-view/examples/test-examples/DisplaysItemView.example';
import OverflowDisplaysItemView from './packages/terra-clinical-item-view/examples/test-examples/OverflowDisplaysItemView.example';
import DefaultLabelValueView from './packages/terra-clinical-label-value-view/examples/test-examples/DefaultLabelValueView.example';
import MultipleValueLabelValueView from './packages/terra-clinical-label-value-view/examples/test-examples/MultipleValueLabelValueView.example';
import NodeValueLabelValueView from './packages/terra-clinical-label-value-view/examples/test-examples/NodeValueLabelValueView.example';
import TextValueLabelValueView from './packages/terra-clinical-label-value-view/examples/test-examples/TextValueLabelValueView.example';
import ContentNoDataView from './packages/terra-clinical-no-data-view/tests/nightwatch/ContentNoDataView';
import DefaultNoDataView from './packages/terra-clinical-no-data-view/tests/nightwatch/DefaultNoDataView';
import HiddenNoDataView from './packages/terra-clinical-no-data-view/tests/nightwatch/HiddenNoDataView';
import TextNoDataView from './packages/terra-clinical-no-data-view/tests/nightwatch/TextNoDataView';
import Default from './packages/terra-clinical-onset-picker/examples/test-examples/Default.example';
import FiveYears from './packages/terra-clinical-onset-picker/examples/test-examples/FiveYears.example';
import LessMonth from './packages/terra-clinical-onset-picker/examples/test-examples/LessMonth.example';
import LessYear from './packages/terra-clinical-onset-picker/examples/test-examples/LessYear.example';

const componentConfig = {
  'terra-clinical-action-header': {
    name: 'Clinical Action Header',
    path: '/clinical-action-header',
    tests: [
      {
        name: 'Back Action Header',
        path: '/back-action-header',
        component: BackActionHeader,
      },
      {
        name: 'Back Close Action Header',
        path: '/back-close-action-header',
        component: BackCloseActionHeader,
      },
      {
        name: 'Children Action Header',
        path: '/children-action-header',
        component: ChildrenActionHeader,
      },
      {
        name: 'Close Action Header',
        path: '/close-action-header',
        component: CloseActionHeader,
      },
      {
        name: 'Default Action Header',
        path: '/default-action-header',
        component: DefaultActionHeader,
      },
      {
        name: 'Keep Close Button Action Header',
        path: '/keep-close-button-action-header',
        component: KeepCloseButtonActionHeader,
      },
      {
        name: 'Maximize Action Header',
        path: '/maximize-action-header',
        component: MaximizeActionHeader,
      },
      {
        name: 'Minimize Action Header',
        path: '/minimize-action-header',
        component: MinimizeActionHeader,
      },
      {
        name: 'Previous Next Action Header',
        path: '/previous-next-action-header',
        component: PreviousNextActionHeader,
      },
      {
        name: 'Title Action Header',
        path: '/title-action-header',
        component: TitleActionHeader,
      },
    ],
  },
  'terra-clinical-application': {
    name: 'Clinical Application',
    path: '/clinical-application',
    pages: [
      {
        name: 'Index',
        path: '/index',
        component: TerraClinicalApplicationIndex,
      },
    ],
    tests: [
      {
        name: 'Default Application',
        path: '/default-application',
        component: DefaultApplication,
      },
      {
        name: 'No App Delegate Application',
        path: '/no-app-delegate-application',
        component: NoAppDelegateApplication,
      },
    ],
  },
  'terra-clinical-detail-view': {
    name: 'Clinical Detail View',
    path: '/clinical-detail-view',
    tests: [
      {
        name: 'Detail List',
        path: '/detail-list',
        tests: [
          {
            name: 'Large Item List',
            path: '/large-item-list',
            component: LargeItemList,
          },
          {
            name: 'Normal Item List',
            path: '/normal-item-list',
            component: NormalItemList,
          },
        ],
      },
      {
        name: 'Detail List Item',
        path: '/detail-list-item',
        tests: [
          {
            name: 'Default List Item',
            path: '/default-list-item',
            component: DefaultListItem,
          },
        ],
      },
      {
        name: 'Detail View',
        path: '/detail-view',
        tests: [
          {
            name: 'Detail View Divided',
            path: '/detail-view-divided',
            component: DetailViewDivided,
          },
          {
            name: 'Detail View No Divider',
            path: '/detail-view-no-divider',
            component: DetailViewNoDivider,
          },
        ],
      },
    ],
  },
  'terra-clinical-error-view': {
    name: 'Clinical Error View',
    path: '/clinical-error-view',
    tests: [
      {
        name: 'Button Error View',
        path: '/button-error-view',
        component: ButtonErrorView,
      },
      {
        name: 'Default Error View',
        path: '/default-error-view',
        component: DefaultErrorView,
      },
      {
        name: 'Hidden Error View',
        path: '/hidden-error-view',
        component: HiddenErrorView,
      },
      {
        name: 'Text Error View',
        path: '/text-error-view',
        component: TextErrorView,
      },
    ],
  },
  'terra-clinical-header': {
    name: 'Clinical Header',
    path: '/clinical-header',
    tests: [
      {
        name: 'Default Header',
        path: '/default-header',
        component: DefaultHeader,
      },
      {
        name: 'Left And Right Content Header',
        path: '/left-and-right-content-header',
        component: LeftAndRightContentHeader,
      },
      {
        name: 'Left And Right Content Subheader',
        path: '/left-and-right-content-subheader',
        component: LeftAndRightContentSubheader,
      },
      {
        name: 'Left Content Header',
        path: '/left-content-header',
        component: LeftContentHeader,
      },
      {
        name: 'Long Title And Content Header',
        path: '/long-title-and-content-header',
        component: LongTitleAndContentHeader,
      },
      {
        name: 'Long Title Header',
        path: '/long-title-header',
        component: LongTitleHeader,
      },
      {
        name: 'No Title Right Content Header',
        path: '/no-title-right-content-header',
        component: NoTitleRightContentHeader,
      },
      {
        name: 'Right Content Header',
        path: '/right-content-header',
        component: RightContentHeader,
      },
      {
        name: 'Title Header',
        path: '/title-header',
        component: TitleHeader,
      },
    ],
  },
  'terra-clinical-item-collection': {
    name: 'Clinical Item Collection',
    path: '/clinical-item-collection',
    tests: [
      {
        name: 'Item Collection All Elements',
        path: '/item-collection-all-elements',
        component: ItemCollectionAllElements,
      },
      {
        name: 'Item Collection Item Styles',
        path: '/item-collection-item-styles',
        component: ItemCollectionItemStyles,
      },
      {
        name: 'Item Collection List Styles',
        path: '/item-collection-list-styles',
        component: ItemCollectionListStyles,
      },
      {
        name: 'Item Collection Selectable',
        path: '/item-collection-selectable',
        component: ItemCollectionSelectable,
      },
      {
        name: 'Item Collection Table Styles',
        path: '/item-collection-table-styles',
        component: ItemCollectionTableStyles,
      },
      {
        name: 'Item Collection Varying Items',
        path: '/item-collection-varying-items',
        component: ItemCollectionVaryingItems,
      },
    ],
  },
  'terra-clinical-item-display': {
    name: 'Clinical Item Display',
    path: '/clinical-item-display',
    tests: [
      {
        name: 'Comment',
        path: '/comment',
        tests: [
          {
            name: 'Default Item Comment',
            path: '/default-item-comment',
            component: DefaultItemComment,
          },
          {
            name: 'Text Item Comment',
            path: '/text-item-comment',
            component: TextItemComment,
          },
        ],
      },
      {
        name: 'Display',
        path: '/display',
        tests: [
          {
            name: 'Default Item Display',
            path: '/default-item-display',
            component: DefaultItemDisplay,
          },
          {
            name: 'Disabled Item Display',
            path: '/disabled-item-display',
            component: DisabledItemDisplay,
          },
          {
            name: 'Icon Item Display',
            path: '/icon-item-display',
            component: IconItemDisplay,
          },
          {
            name: 'Scaling Icon Item Display',
            path: '/scaling-icon-item-display',
            component: ScalingIconItemDisplay,
          },
          {
            name: 'Text Style Item Display',
            path: '/text-style-item-display',
            component: TextStyleItemDisplay,
          },
        ],
      },
    ],
  },
  'terra-clinical-item-view': {
    name: 'Clinical Item View',
    path: '/clinical-item-view',
    tests: [
      {
        name: 'Accessory Item View',
        path: '/accessory-item-view',
        component: AccessoryItemView,
      },
      {
        name: 'Comment Item View',
        path: '/comment-item-view',
        component: CommentItemView,
      },
      {
        name: 'Default Item View',
        path: '/default-item-view',
        component: DefaultItemView,
      },
      {
        name: 'Displays Item View',
        path: '/displays-item-view',
        component: DisplaysItemView,
      },
      {
        name: 'Overflow Displays Item View',
        path: '/overflow-displays-item-view',
        component: OverflowDisplaysItemView,
      },
    ],
  },
  'terra-clinical-label-value-view': {
    name: 'Clinical Label Value View',
    path: '/clinical-label-value-view',
    tests: [
      {
        name: 'Default Label Value View',
        path: '/default-label-value-view',
        component: DefaultLabelValueView,
      },
      {
        name: 'Multiple Value Label Value View',
        path: '/multiple-value-label-value-view',
        component: MultipleValueLabelValueView,
      },
      {
        name: 'Node Value Label Value View',
        path: '/node-value-label-value-view',
        component: NodeValueLabelValueView,
      },
      {
        name: 'Text Value Label Value View',
        path: '/text-value-label-value-view',
        component: TextValueLabelValueView,
      },
    ],
  },
  'terra-clinical-no-data-view': {
    name: 'Clinical No Data View',
    path: '/clinical-no-data-view',
    tests: [
      {
        name: 'Content No Data View',
        path: '/content-no-data-view',
        component: ContentNoDataView,
      },
      {
        name: 'Default No Data View',
        path: '/default-no-data-view',
        component: DefaultNoDataView,
      },
      {
        name: 'Hidden No Data View',
        path: '/hidden-no-data-view',
        component: HiddenNoDataView,
      },
      {
        name: 'Text No Data View',
        path: '/text-no-data-view',
        component: TextNoDataView,
      },
    ],
  },
  'terra-clinical-onset-picker': {
    name: 'Clinical Onset Picker',
    path: '/clinical-onset-picker',
    tests: [
      {
        name: 'Default',
        path: '/default',
        component: Default,
      },
      {
        name: 'Five Years',
        path: '/five-years',
        component: FiveYears,
      },
      {
        name: 'Less Month',
        path: '/less-month',
        component: LessMonth,
      },
      {
        name: 'Less Year',
        path: '/less-year',
        component: LessYear,
      },
    ],
  },
  'terra-clinical-site': {
    name: 'Clinical Site',
    path: '/clinical-site',
    pages: [
      {
        name: 'Action Header',
        path: '/action-header',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex,
          },
        ],
      },
      {
        name: 'Detail View',
        path: '/detail-view',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex1,
          },
        ],
      },
      {
        name: 'Error View',
        path: '/error-view',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex2,
          },
        ],
      },
      {
        name: 'Header',
        path: '/header',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex3,
          },
        ],
      },
      {
        name: 'Item Collection',
        path: '/item-collection',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex4,
          },
        ],
      },
      {
        name: 'Item Display',
        path: '/item-display',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex5,
          },
        ],
      },
      {
        name: 'Item View',
        path: '/item-view',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex6,
          },
        ],
      },
      {
        name: 'Label Value View',
        path: '/label-value-view',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex7,
          },
        ],
      },
      {
        name: 'No Data View',
        path: '/no-data-view',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex8,
          },
        ],
      },
      {
        name: 'Onset Picker',
        path: '/onset-picker',
        pages: [
          {
            name: 'Index',
            path: '/index',
            component: TerraClinicalSiteIndex9,
          },
        ],
      },
    ],
  },
};

export default componentConfig;
